In [1]:
import numpy as np
import pandas as pd

import os

In [2]:
data_folder = './Data_Q4/'

In [3]:
df = pd.read_csv(os.path.join(data_folder, 'Q4_Data.csv'))

In [4]:
df.head()

A   B   C   D  E  F
0   2   2  36  34  0  0
1   2   5   6   1  0  1
2   4   7  17   9  2  1
3  10  10  24  11  0  3
4   3   2   3   1  0  1

In [5]:
def sqr_dist(o, c):
    # because all distance will be squared then
    # no sqrt to simplify it
    return np.sum(np.square(o-c))

def wt(o, c1, c2):
    return sqr_dist(o, c2) / (sqr_dist(o, c1)+sqr_dist(o, c2))

In [6]:
def E_step(df, center_set):
    patition_matrix = []
    for i in range(df.shape[0]):
        w1 = wt(df.iloc[i].values, center_set[-1][0], center_set[-1][1])
        patition_matrix.append([w1, 1-w1])
    m = np.array(patition_matrix)
    return m.T

def M_step(df, center_set, pm):
    # for n centers
    center_per_iter = []
    for i in range(center_set.shape[1]):
        c = []
    # for n rows of points
        for j in range(df.shape[1]):
            c.append(np.sum(np.square(pm[i])*df.iloc[:, j]) / np.sum(np.square(pm[i])))
        center_per_iter.append(c)
    center_set = np.append(center_set, [center_per_iter], axis=0)
    return center_set

In [7]:
def sse(m, df, center_set):
    s = 0
    
    for n_c in range(m.shape[0]): # number of clusters
        for n_p in range(m.shape[1]): # number of points
            s += pow(m[n_c][n_p], m.shape[0])*sqr_dist(df.iloc[n_p], center_set[-1][n_c])
    return s

In [8]:
def em_algorithm(df, center_set, least_dist=0.0001):
    
    i = 0
    while i < 100:
        print(f'{i+1}th interation:')
        print('-------------------------')
        m = E_step(df ,center_set)               # step E
        center_set = M_step(df, center_set, m)   # step M
        print('Updated centers are:')
        print(center_set[-1][0], center_set[-1][1])
        sse_value = sse(m, df, center_set)
        print(f'SSE: {sse_value}', '\n')
        if np.sum(abs(center_set[-1]-center_set[-2])) < least_dist:
            break
        i += 1
    print(f'Iteration finished, the maximum is {i+1}')
    print('Final converge centers:')
    print(center_set[-1][0], center_set[-1][1], '\n')

In [9]:
center_set = np.array([[[1,1,1,1,1,1], [0,0,0,0,0,0]]])

em_algorithm(df, center_set, 0.0001)

1th interation:
-------------------------
Updated centers are:
[ 2.69065848  5.55601619 12.26620984  7.48120434  0.24285351  0.99747068] [ 2.98792136  7.30724305 16.48227403 10.65664851  0.23655629  1.00679373]
SSE: 183651.91776531364 

2th interation:
-------------------------
Updated centers are:
[ 2.50680171  4.77056093 10.16570693  5.82192441  0.20821519  0.95235302] [ 3.3178565   8.76258517 20.6221998  13.79747907  0.28891998  1.08775325]
SSE: 174501.5595037977 

3th interation:
-------------------------
Updated centers are:
[2.36078528 4.0238082  8.22101687 4.31693252 0.20201727 0.92755891] [ 3.76216608 10.77192671 26.65297439 18.40471854  0.29970755  1.18854158]
SSE: 157570.4161126244 

4th interation:
-------------------------
Updated centers are:
[2.33320554 3.82436102 7.65732125 3.8902117  0.20822563 0.91743624] [ 4.05557133 12.02241977 30.62255459 21.45949391  0.27981624  1.26556192]
SSE: 149174.0497444281 

5th interation:
-------------------------
Updated centers are:
[2.3